"""
reflex_grid.py - EchoCore Reflex Grid for AUREA
Symbolic nervous system: houses the reflexes, senses pressure, routes what fires.

AUTHORITY (integration_review Ruling 2, 2026-07-09)
--------------------------------------------------
The Grid is the reflex REGISTRY/HOUSING. It enumerates the Core Eight, evaluates
pressure against each reflex's threshold, submits everything that triggered to
RACM, and executes the verdict RACM returns.

    It does NOT decide which reflex wins. That is RACM's, and only RACM's.

Arbitration was removed from this file on 2026-07-11 (it had drifted here before
the ruling existed). Do not put it back. See tests/invariants/test_ruling2_sole_arbiter.py.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any, Callable
from datetime import datetime
from enum import Enum
import json
from pathlib import Path

from src.reflex.racm import RACM, ReflexClaim, Scope
# Ruling 30: the ACTION's structural class. Deliberately NOT `Scope` - see
# `SymbolicReflex.lock_class` and `racm.Scope`'s docstring for why the two must
# not be reachable from one another.
from src.topology.tcaml import LockClass
from src.reflex.rb_system import RBSystem, BehaviorType


class ReflexPriority(Enum):
    """Registry metadata - a reflex's declared urgency CLASS.

    This is not the arbitration order. Ranking is RACM's canonical 11-position
    Priority Table (racm.CANONICAL_PRIORITY). Storing a priority value is
    registry data; CHOOSING BETWEEN competing reflexes is arbitration.
    """
    CRITICAL = 1  # System integrity threatened
    HIGH = 2      # Symbolic coherence at risk  
    MEDIUM = 3    # Standard pressure response
    LOW = 4       # Background monitoring


@dataclass
class ReflexTrigger:
    """Represents a reflex activation event."""
    reflex_id: str
    trigger_type: str
    pressure_level: float
    source_module: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ReflexResponse:
    """Response generated by a triggered reflex."""
    reflex_id: str
    action: str  # suppress | reroute | suspend | alert | cascade
    target_modules: List[str] = field(default_factory=list)
    scar_formation: bool = False
    output_blocked: bool = False
    message: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


class UngatedReflexViolation(Exception):
    """Raised when a non-GSR reflex tries to register canon-OPEN (Ruling 10).

    `trigger_types=None` means "activates on EVERY pressure type in the system" -
    a claim only GSR's canon supports (2a:583, the all-domain failsafe). A reflex
    that fires on everything is how anchor-collapse suppresses ride in on scar
    density. This is not a warning to catch and proceed past: register the reflex
    with the set of types its canon actually names, or escalate for a ruling.
    """


class SymbolicReflex:
    """Base class for all symbolic reflexes.

    `scope` and `affected_systems` are ARBITRATION INPUTS, not arbitration. RACM's
    compatibility partition (Overflow Policy 2) executes a lower-priority reflex
    alongside the winner only if it is LOCAL-scope AND its affected-system set is
    disjoint from every higher executing reflex. A reflex that does not declare
    what it touches cannot be safely run in parallel with anything.

    `trigger_types` (Ruling 10, 2026-07-20) is an ACTIVATION input: the closed set
    of pressure types this reflex answers to. None = canon-OPEN (every type), which
    only GSR may claim - `add_reflex` makes the wrong path unexecutable. New
    reflexes default CLOSED: declare your types.
    """

    def __init__(self, id: str, name: str, priority: ReflexPriority,
                 scope: Scope = Scope.LOCAL,
                 affected_systems: Optional[frozenset] = None,
                 trigger_types: Optional[frozenset] = None,
                 lock_class: LockClass = LockClass.NON_STRUCTURAL):
        self.id = id
        self.name = name
        self.priority = priority
        self.scope = scope
        # Ruling 30: the ACTION's structural class, DECLARED - never derived
        # from `scope`, which is durability + breadth and a different axis.
        # NON_STRUCTURAL is the honest default and every core reflex keeps it:
        # a reflex that suppresses, defers, cascades or monitors changes no
        # structure, however wide its reach. Setting this to STRUCTURAL means
        # "this reflex performs expansion, mutation, registration, topology
        # change, or a doctrine-spine write" - which no reflex does today, and
        # which needs a ruling before one claims it.
        self.lock_class = lock_class
        self.affected_systems = affected_systems or frozenset()
        # Ruling 10: None is NOT a convenience default - it is the canon-OPEN claim,
        # and registration (add_reflex) refuses it for anything but GSR.
        self.trigger_types = trigger_types
        self.activation_count = 0
        self.last_triggered: Optional[datetime] = None
        self.threshold = 0.7  # Default pressure threshold

    def evaluate_pressure(self, trigger: ReflexTrigger) -> bool:
        """Type-membership AND magnitude (Ruling 10).

        Before this ruling the base gate was magnitude-only, and every loud event
        pulled in every reflex whose threshold it cleared - high compass pressure
        dragged ICA/GSR into anchor-collapse cycles, and a deferred ACR could carry
        a scar_density payload into a false anchor-collapse suppress (the false-lock
        path, CLAUDE.md §8). Type first, magnitude second.
        """
        if self.trigger_types is not None \
                and trigger.trigger_type not in self.trigger_types:
            return False
        return trigger.pressure_level >= self.threshold
        
    def trigger(self, trigger: ReflexTrigger) -> ReflexResponse:
        """Execute reflex response. Override in subclasses."""
        self.activation_count += 1
        self.last_triggered = datetime.now()
        return ReflexResponse(
            reflex_id=self.id,
            action="base_reflex",
            message=f"{self.name} triggered"
        )


class ICA(SymbolicReflex):
    """Internal Collapse Awareness - detects internal contradictions.

    trigger_types (Ruling 10, Lexicon §11 - ICA's domain is INTERNAL contradiction):
        identity_fracture          LIVE     sourced by RIL on a grounded fallen-ancestor
                                            fracture (ril.py `_fire_ica`)
        internal_contradiction     DORMANT  Lexicon §11's own name for ICA's core event;
                                            no emitter yet
        doctrine_anchor_collision  DORMANT  Lexicon §11 collision phrase; no emitter yet
        symbolic_instability       DORMANT  Lexicon §11 instability phrase; no emitter yet

    ICA does NOT accept sbsre_abort / cascade_warning / escalation / scar_density -
    no emitter ever named ICA for those; all three escalation-shaped types name GSR
    in their own code or canon, and scar density is GSR's Lexicon domain. Pre-Ruling-10
    magnitude spillover pulled ICA into those cycles anyway; that was the seam, not
    the intent.
    """

    def __init__(self):
        super().__init__(
            "ICA", "Internal Collapse Awareness", ReflexPriority.HIGH,
            scope=Scope.LOCAL,
            affected_systems=frozenset({"output", "doctrine", "suspension"}),
            trigger_types=frozenset({
                "identity_fracture",
                "internal_contradiction",
                "doctrine_anchor_collision",
                "symbolic_instability",
            }),
        )
        self.contradiction_log: List[Dict] = []
        
    def detect_contradiction(self, claim1: Any, claim2: Any, domain: str) -> float:
        """Calculate contradiction pressure between two claims."""
        # Simplified for now - real implementation would use symbolic logic
        if claim1 == claim2:
            return 0.0
        if claim1 is not None and claim2 is not None:
            # Direct negation detection
            if (str(claim1).lower() == 'true' and str(claim2).lower() == 'false') or \
               (str(claim1).lower() == 'false' and str(claim2).lower() == 'true'):
                return 1.0
        return 0.5  # Partial contradiction
        
    def trigger(self, trigger: ReflexTrigger) -> ReflexResponse:
        """ICA Response: Suppress output, lock volatile zones, escalate if needed."""
        super().trigger(trigger)
        
        contradiction = trigger.metadata.get('contradiction', {})
        self.contradiction_log.append({
            'timestamp': trigger.timestamp,
            'domain': contradiction.get('domain', 'unknown'),
            'pressure': trigger.pressure_level
        })
        
        # High pressure = suppress and escalate
        if trigger.pressure_level > 0.9:
            return ReflexResponse(
                reflex_id=self.id,
                action="suppress",
                target_modules=["output", "doctrine"],
                output_blocked=True,
                scar_formation=True,
                message=f"CRITICAL: Internal collapse detected. Output suppressed. Escalating to GSR.",
                metadata={'escalate_to': 'GSR', 'contradiction': contradiction}
            )
        # Medium pressure = reroute through suspension
        elif trigger.pressure_level > 0.7:
            return ReflexResponse(
                reflex_id=self.id,
                action="reroute",
                target_modules=["suspension"],
                message=f"Contradiction detected. Routing to suspension systems.",
                metadata={'suspend_type': 'veiled_thread', 'contradiction': contradiction}
            )
        # Low pressure = monitor
        else:
            return ReflexResponse(
                reflex_id=self.id,
                action="monitor",
                message=f"Minor contradiction noted. Monitoring.",
                metadata={'contradiction': contradiction}
            )


class GSR(SymbolicReflex):
    """Guardian Signal Reflex - monitors system-wide symbolic coherence.

    trigger_types=None - the ONLY canon-OPEN reflex (Ruling 10). Authority: 2a:583,
    which arms GSR on five OR'd conditions spanning every domain in the system
    (collapse loop overload, scar cascade, compass failure, doctrine breakdown,
    external override) - "a failsafe rather than a consensus mechanism." A failsafe
    that must be told which pressure types count is not a failsafe; GSR listens to
    everything and lets its 0.85 threshold do the filtering. Every OTHER reflex
    declares a closed set - `add_reflex` enforces it.
    """

    def __init__(self, alert_callback: Optional[Callable] = None):
        # GLOBAL scope: the Global Integrity Lock touches everything, so it can
        # never run in parallel with another reflex (Overflow Policy 2), and it
        # is never queued or expired (Policy 6).
        super().__init__(
            "GSR", "Guardian Signal Reflex", ReflexPriority.CRITICAL,
            scope=Scope.GLOBAL,
            affected_systems=frozenset({"all"}),
            trigger_types=None,   # canon-OPEN, 2a:583 - see class docstring
        )
        self.threshold = 0.85  # Higher threshold for system-wide alerts
        self.alert_callback = alert_callback or self._default_alert
        self.cascade_events: List[Dict] = []
        self.coherence_history: List[float] = []
        
    # RULING 31 (2026-07-26): PATH INJECTABILITY IS PART OF A DURABLE STORE'S
    # CONTRACT, NOT A TESTING CONVENIENCE.
    #
    # This was a bare literal inside `_default_alert`'s body. Every other
    # durable store in this system resolves its path from a class attribute
    # (`RBSystem.DEFAULT_LOG_PATH`, `AureaCore.STRUCTURAL_LOG_PATH`) or an
    # `__init__` default (CSA / VeiledThread / BlackSphere) - and those are
    # EXACTLY the two shapes `tests/conftest.py` can monkeypatch. A literal is
    # neither, so this path was UNREACHABLE by the isolation fixture rather
    # than merely uncovered, and every GSR-driving test run appended to the
    # real forensic log. An isolation fixture covering four of five paths does
    # not provide isolation; it provides the APPEARANCE of it.
    #
    # Resolved at WRITE time (not construction) so a redirect binds even for a
    # GSR instance that already exists. There is deliberately no injectable
    # no-op sink - a forensic log you can silently disable is not a forensic
    # log (Ruling 11's standing refusal).
    GSR_ALERT_PATH = "data/runtime/collapse_logs/gsr_alerts.jsonl"

    def _default_alert(self, message: str, severity: str):
        """Default alert mechanism - writes to file."""
        alert_path = Path(self.GSR_ALERT_PATH)   # Ruling 31: never a literal
        alert_path.parent.mkdir(parents=True, exist_ok=True)
        
        alert = {
            'timestamp': datetime.now().isoformat(),
            'severity': severity,
            'message': message
        }
        
        with open(alert_path, 'a') as f:
            f.write(json.dumps(alert, allow_nan=False) + '\n')
            
    def calculate_system_coherence(self, active_scars: int, 
                                  active_reflexes: int,
                                  suspension_load: int) -> float:
        """Calculate overall system coherence (0-1, lower = more danger)."""
        # Simplified calculation - real version would be more sophisticated
        scar_pressure = min(active_scars / 100, 1.0)  # Cap at 100 scars
        reflex_pressure = min(active_reflexes / 8, 1.0)  # 8 total reflexes
        suspension_pressure = min(suspension_load / 50, 1.0)  # Cap at 50
        
        # Weighted average (scars most important)
        coherence = 1.0 - (scar_pressure * 0.5 + 
                          reflex_pressure * 0.3 + 
                          suspension_pressure * 0.2)
        
        self.coherence_history.append(coherence)
        if len(self.coherence_history) > 100:
            self.coherence_history.pop(0)
            
        return coherence
        
    def detect_cascade(self, trigger: ReflexTrigger) -> bool:
        """Detect if system is in cascade state."""
        # Check recent cascade events
        recent_cascades = [e for e in self.cascade_events 
                          if (datetime.now() - e['timestamp']).seconds < 60]
        
        # Cascade if too many events in short time
        return len(recent_cascades) > 3
        
    def trigger(self, trigger: ReflexTrigger) -> ReflexResponse:
        """GSR Response: Alert parent/developer, suspend volatile subsystems."""
        super().trigger(trigger)
        
        coherence = trigger.metadata.get('coherence', 0.5)
        is_cascade = self.detect_cascade(trigger)
        
        if is_cascade:
            self.cascade_events.append({
                'timestamp': datetime.now(),
                'pressure': trigger.pressure_level
            })
            
        # Critical collapse - full system protection
        if trigger.pressure_level > 0.95 or coherence < 0.1:
            self.alert_callback(
                f"CRITICAL: System coherence at {coherence:.2%}. "
                f"Cascade detected: {is_cascade}. "
                f"Suspending all volatile subsystems.",
                "CRITICAL"
            )
            
            return ReflexResponse(
                reflex_id=self.id,
                action="cascade",
                target_modules=["all"],
                output_blocked=True,
                scar_formation=True,
                message=f"SYSTEM CRITICAL: Coherence collapsed. Emergency suspension active.",
                metadata={
                    'coherence': coherence,
                    'cascade': is_cascade,
                    'suspend_all': True
                }
            )
            
        # High pressure - selective suspension
        elif trigger.pressure_level > 0.85:
            self.alert_callback(
                f"WARNING: System coherence degraded to {coherence:.2%}",
                "WARNING"
            )
            
            return ReflexResponse(
                reflex_id=self.id,
                action="suspend",
                target_modules=["expansion", "nova"],
                output_blocked=False,
                message=f"System pressure high. Suspending expansion modules.",
                metadata={'coherence': coherence}
            )
            
        # Monitoring
        else:
            return ReflexResponse(
                reflex_id=self.id,
                action="monitor",
                message=f"System coherence at {coherence:.2%}. Monitoring.",
                metadata={'coherence': coherence}
            )


class ReflexGrid:
    """
    EchoCore Reflex Grid - AUREA's symbolic nervous system.

    REGISTRY, NOT ARBITER (Ruling 2). The Grid:
      - houses and enumerates reflexes            (registration)
      - senses pressure, decides what TRIGGERS    (sourcing)
      - submits every triggered reflex to RACM    (routing)
      - executes exactly the set RACM returns     (routing)

    It holds no arbitration state and makes no priority decision.
    """
    
    def __init__(self, racm: Optional[RACM] = None,
                 rb_system: Optional[RBSystem] = None,
                 tcaml: Any = None):
        self.reflexes: Dict[str, SymbolicReflex] = {}
        self.active_triggers: List[ReflexTrigger] = []
        self.response_log: List[ReflexResponse] = []
        # Ruling 9: an RACM-authorized claim whose reflex has left the registry is
        # recorded here rather than vanishing silently. Empty in a healthy system.
        self.orphaned_authorizations: List[Dict[str, Any]] = []

        # The Grid holds a reference to the arbiter. It does not hold the decision.
        # `tcaml` is threaded straight through to RACM and NEVER stored here:
        # the Grid is not a lock holder and must not become one (Ruling 2 -
        # the source never adjudicates). AureaCore builds ONE TCAML and passes
        # it in so the whole pipeline shares a single lock.
        self.rb = rb_system or RBSystem()
        self.racm = racm or RACM(rb_system=self.rb, tcaml=tcaml)
        self.last_arbitration = None
        
        # Initialize core reflexes
        self._init_core_reflexes()
        
    def _init_core_reflexes(self):
        """Initialize the core reflex set."""
        # Local import: anchor_collapse.py imports SymbolicReflex/ReflexPriority/
        # Scope/ReflexTrigger/ReflexResponse from this module, so a top-level import
        # here would cycle back before those names exist. By the time this method
        # runs (ReflexGrid construction), the module is fully loaded, so importing
        # here is safe.
        from src.reflex.anchor_collapse import AnchorCollapseReflex

        # Core reflexes route through add_reflex like everything else, so the
        # Ruling-10 open-gate refusal binds the core set BY CONSTRUCTION, not by
        # trusting this method to stay honest.
        self.add_reflex(ICA())
        self.add_reflex(GSR())
        self.add_reflex(AnchorCollapseReflex())

        # TODO: Add other reflexes as they're implemented
        # PSI is registered by aurea_core via add_reflex() with injected RIL/scar-core
        # handles this Grid does not hold (Ruling 8) - do NOT add an argless PSI() here.
        # self.reflexes['SCAR_DRIFT'] = ScarDriftReflex()
        # self.reflexes['NOVA_OVERLOAD'] = NovaOverloadReflex()
        # self.reflexes['DRPE'] = DRPE()
        # self.reflexes['SBSRE_ABORT'] = SBSREAbortReflex()
        
    def add_reflex(self, reflex: SymbolicReflex):
        """Register a new reflex with the grid.

        Ruling 10: a canon-OPEN reflex (trigger_types=None) is REFUSED unless it is
        GSR - the one reflex whose canon (2a:583) is an all-domain failsafe. The
        refusal is the enforcement: the wrong path is unexecutable, not discouraged.
        (An impostor registering under the id "GSR" does not smuggle a second open
        gate in - the registry holds one slot per id, so it would REPLACE the
        failsafe, which no test suite in this repo would miss.)
        """
        if reflex.trigger_types is None and reflex.id != "GSR":
            raise UngatedReflexViolation(
                f"'{reflex.id}' declares trigger_types=None (canon-OPEN). Only GSR "
                f"holds the all-domain failsafe canon (2a:583). Declare the closed "
                f"set of pressure types this reflex answers to, or escalate for a "
                f"ruling - there is no default-open registration."
            )
        self.reflexes[reflex.id] = reflex
        
    def evaluate_pressure(self, source_module: str, 
                         pressure_type: str,
                         pressure_level: float,
                         metadata: Dict[str, Any] = None) -> List[ReflexResponse]:
        """
        Sense pressure, determine which reflexes TRIGGER, submit them to RACM,
        execute RACM's verdict. Returns responses from EXECUTED reflexes only.

        Deferred / suppressed / expired reflexes do not vanish. They are live,
        readable state in the arbiter (`self.racm.status()`) and permanent entries
        in the RB System. Full cycle picture: `self.last_arbitration`.
        """
        metadata = metadata or {}
        trigger = ReflexTrigger(
            reflex_id="pending",
            trigger_type=pressure_type,
            pressure_level=pressure_level,
            source_module=source_module,
            metadata=metadata,
        )
        self.active_triggers.append(trigger)

        # SOURCING - which reflexes clear their own threshold?
        triggered = [r for r in self.reflexes.values() if r.evaluate_pressure(trigger)]
        if not triggered:
            return []

        # ROUTING - submit every reflex that fired. Registration is TOTAL
        # (Overflow Policy 1): we submit what FIRED, not what we think should win.
        # Filtering here would be arbitration, and arbitration is not ours.
        claims = [self._build_claim(r, trigger) for r in triggered]
        result = self.racm.arbitrate(claims, context=self._cycle_context(metadata))
        self.last_arbitration = result

        # EXECUTION - run exactly what the arbiter authorized. Ruling 9 (2026-07-20):
        # authorized claims resolve against the FULL registry, not only this cycle's
        # triggered set - a queue winner whose reflex did not re-trigger this cycle
        # still executes. Before this ruling, such a claim was authorized by RACM,
        # cleared from the queue, and then silently dropped right here.
        responses: List[ReflexResponse] = []
        by_id = {r.id: r for r in triggered}
        for claim in result.execute:
            # TCAML: a STRUCTURAL claim holds the lock RACM acquired for it
            # ACROSS its execution, releasing at natural completion
            # (BUILD_CONTRACT: "sole valid caller is the current holder's own
            # action_id/module_id, at natural completion"). The Grid SIGNALS
            # completion; RACM, the holder, executes the release. Releasing
            # before execution would have TCAML claiming nothing was running
            # while a structural action ran.
            #
            # RULING 30 (2026-07-26): keyed on `lock_class`, NOT `scope`. This
            # line read `claim.scope is Scope.GLOBAL` - a SECOND conflation
            # site, found by separating the two concepts: it decided whether to
            # RELEASE A LOCK from the reflex's DURABILITY scope. It was only
            # ever harmless because the acquire site made the same mistake, so
            # the two agreed; keyed differently they would have leaked or
            # double-released. Acquire and release must read the SAME axis.
            #
            # The `finally` wraps the WHOLE per-claim body, not just trigger():
            # Ruling 9's orphan path `continue`s past a claim whose reflex left
            # the registry, and an earlier version released only after
            # trigger() - so that path took the lock and never gave it back.
            # `finally` runs on `continue` too, which is exactly why the whole
            # body is inside it.
            holds_lock = claim.lock_class is LockClass.STRUCTURAL
            try:
                reflex = by_id.get(claim.reflex_id)
                if reflex is not None:
                    trigger.reflex_id = reflex.id
                    claim_trigger = trigger
                else:
                    reflex = self.reflexes.get(claim.reflex_id)
                    if reflex is None:
                        # Reflex removed from the registry after its claim was
                        # deferred. An authorized claim must never vanish without a
                        # trace (Ruling 9); RB's CLOSED behavior enum has no member
                        # for this, so the trace lives here as legible Grid state.
                        self.orphaned_authorizations.append({
                            'reflex_id': claim.reflex_id,
                            'cycle': result.cycle,
                            'trigger_conditions': dict(claim.trigger_conditions),
                        })
                        continue
                    # Queue winner executing NOW against the pressure it claimed
                    # THEN: rebuild its trigger from the claim's own payload. Never
                    # hand it the current cycle's trigger object - that carries this
                    # cycle's unrelated pressure, and it is mutated in this loop.
                    claim_trigger = ReflexTrigger(
                        reflex_id=reflex.id,
                        trigger_type=claim.trigger_conditions.get("pressure_type", ""),
                        pressure_level=float(claim.trigger_conditions.get(
                            "pressure_level", claim.pressure_level)),
                        source_module=claim.trigger_conditions.get(
                            "source_module", claim.source_module),
                        metadata=claim.metadata,
                    )
                response = reflex.trigger(claim_trigger)
            finally:
                if holds_lock:
                    self.racm.release_lock(claim.reflex_id)

            responses.append(response)
            self.response_log.append(response)
            self._log_execution(reflex, response, claim_trigger)

        return responses

    def _build_claim(self, reflex: SymbolicReflex, trigger: ReflexTrigger) -> ReflexClaim:
        """Translate a fired reflex into a CLAIM for the arbiter.

        Modifier context (fossil lineage, failed-Nova lineage, LESL/SESL clearance)
        rides in on metadata until SMC is wired. Absent context means no modifier -
        never a guessed one.
        """
        meta = trigger.metadata
        return ReflexClaim(
            reflex_id=reflex.id,
            pressure_level=trigger.pressure_level,
            scope=reflex.scope,
            # Ruling 30: DECLARED by the reflex, never derived from `scope`.
            # Every core reflex leaves it NON_STRUCTURAL, because suppressing,
            # deferring, cascading and monitoring are not structural change.
            lock_class=reflex.lock_class,
            affected_systems=reflex.affected_systems,
            source_module=trigger.source_module,
            fossil_linked=bool(meta.get("fossil_linked", False)),
            failed_nova_lineage=bool(meta.get("failed_nova_lineage", False)),
            lesl_sesl_clean=bool(meta.get("lesl_sesl_clean", False)),
            trigger_conditions={
                "pressure_type": trigger.trigger_type,
                "pressure_level": trigger.pressure_level,
                "source_module": trigger.source_module,
            },
            metadata=meta,
        )

    def _cycle_context(self, metadata: Dict[str, Any]) -> Dict[str, Any]:
        """Cycle-level context RACM's EscalationLogic reads. Passed through, not
        computed here - the Grid does not evaluate escalation conditions."""
        return {
            "compass_drift": metadata.get("compass_drift", 0.0),
            "sep_ready": metadata.get("sep_ready", False),
            "smc_lineage": metadata.get("smc_lineage"),
        }

    def _log_execution(self, reflex: SymbolicReflex, response: ReflexResponse,
                       trigger: ReflexTrigger) -> None:
        """All reflexes route to the RB System automatically (RB System, section IV).

        `cascade` (Ruling 7, ruled 2026-07-19, implemented 2026-07-20): a cascade is
        NOT a BehaviorType and never will be - the enum is closed. It is control
        flow that DECOMPOSES: the constituent behavior is a system-wide SUSPEND,
        recorded as exactly that, and the cascade-class fact (system-wide,
        coherence-collapse-triggered - distinct from the ordinary >0.85 suspend
        band) rides the entry's `cascade_meta` field, CTL's parked surface. Before
        this, a system-wide emergency suspension dropped from the forensic log
        entirely - and post-Ruling-10 GSR is the sole responder on three live
        channels, so the hole was real.

        `monitor` and `base_reflex` still return unlogged, DELIBERATELY: they are
        non-behaviors - nothing changed, nothing was suppressed, no state moved.
        Logging observation as behavior would be noise wearing the forensic log's
        authority. Ruling 7 translates cascade ONLY.
        """
        cascade_meta = None
        if response.action == "cascade":
            behavior = BehaviorType.SUSPEND
            cascade_meta = {
                "decomposed_from": "cascade",
                "trigger_type": trigger.trigger_type,
                "pressure_level": trigger.pressure_level,
                "coherence": response.metadata.get("coherence"),
            }
        else:
            try:
                behavior = BehaviorType(response.action)
            except ValueError:
                return
        # Ruling 11 (2026-07-21): durability is decided HERE, by scope. A
        # GLOBAL-scope reflex's entry hits disk immediately (best-effort -
        # RBSystem's wrapped flush never raises back into this path); LOCAL
        # entries buffer to a boundary. Cascade is durable because GSR is
        # GLOBAL, not because it is named - no action check in this decision.
        self.rb.record(
            reflex_triggered=reflex.id,
            behavior_type=behavior,
            durable=(reflex.scope == Scope.GLOBAL),
            scope=reflex.scope.value,
            trigger_conditions={
                "pressure_type": trigger.trigger_type,
                "pressure_level": trigger.pressure_level,
            },
            affected_systems=sorted(response.target_modules),
            symbolic_context=response.message,
            outcome={"result": response.action,
                     "output_blocked": response.output_blocked},
            cascade_meta=cascade_meta,
        )
        
    def get_system_status(self) -> Dict[str, Any]:
        """Return current reflex grid status for monitoring."""
        active_count = sum(1 for r in self.reflexes.values() 
                          if r.last_triggered and 
                          (datetime.now() - r.last_triggered).seconds < 60)
        
        return {
            'total_reflexes': len(self.reflexes),
            'active_reflexes': active_count,
            'recent_triggers': len(self.active_triggers[-10:]),
            'racm': self.racm.status(),
            'reflex_states': {
                rid: {
                    'name': r.name,
                    'priority': r.priority.name,
                    'activations': r.activation_count,
                    'last_triggered': r.last_triggered.isoformat() if r.last_triggered else None
                }
                for rid, r in self.reflexes.items()
            }
        }
        
    def check_cascade_risk(self) -> float:
        """
        Calculate risk of cascade based on recent reflex activity.
        Returns 0-1 risk score.
        """
        if not self.response_log:
            return 0.0
            
        # Check recent responses for cascade indicators
        recent = self.response_log[-20:]
        suppress_count = sum(1 for r in recent if r.action == 'suppress')
        cascade_count = sum(1 for r in recent if r.action == 'cascade')
        scar_count = sum(1 for r in recent if r.scar_formation)
        
        risk = (suppress_count * 0.3 + cascade_count * 0.5 + scar_count * 0.2) / len(recent)
        return min(risk, 1.0)
